### ISSUE TITLE
Write "Contact" Page

### ISSUE THREAD

**Issue by QuantumManiac** [waterloo-rocketry/website-react#23]
The [Contact page](https://www.waterloorocketry.com/contact) is yet to be copied over from the original website, as can be seen [here](https://waterloo-rocketry.github.io/website-react/contact).

This is the last page required to have page parity with the original website.

**Comment by QuantumManiac** [comment]
@Subham5401 Sounds good! I'll follow-up on Slack.

**Comment by QuantumManiac** [comment]
@Subham5401 Thanks for your interest! Are you a member of [Waterloo Rocketry](https://www.waterloorocketry.com/) at the University of Waterloo? Unfortunately, we're only offering work to students that are within the team at this time.

**Comment by Subham5401** [comment]
Thank you for sharing your criteria with me. If the opportunity arises, I would be interested in contributing in the future.

**Comment by QuantumManiac** [comment]
closed by #26
