### ISSUE TITLE
Add Launch Canada 2023 trophy to Awards page

### ISSUE THREAD

**Issue by kylemtam** [waterloo-rocketry/website-react#33]
Need a nice photo of the trophy as well (see CANRGX Outreach photo for ideas on how to take that photo as that one was clear and taken against a solid background)

**Comment by QuantumManiac** [comment]
@kylemtam provided us with a pic of the trophy a bit ago: https://waterloorocketry.slack.com/archives/C6BLGAR7H/p1699854174051359
